import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { intentOptions, people, places, socialTables } from "./schema";

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set");
  const stripped = url.replace(/[?&]sslrootcert=[^&]*/g, "").replace(/[?&]sslmode=[^&]*/g, "").replace(/[?]$/, "");
  const sql = postgres(stripped, { ssl: url.includes("pg.psdb.cloud") || url.includes("ssl") ? "require" : false });
  const db = drizzle(sql);

  const existing = await db.select().from(intentOptions);
  if (existing.length > 0) {
    console.log("Already seeded — skipping.");
    await sql.end();
    return;
  }

  await db.insert(intentOptions).values([
    { key: "work", query: "quiet cafe to work from", label: "Deep work", thesis: "Prioritize low noise, long-stay seating, outlets, and repeatability.", ranking: ["Noise fit", "Seat dwell", "Outlet density", "Return ritual"], sortOrder: 0 },
    { key: "supper", query: "late-night supper near me", label: "Late supper", thesis: "Favor open kitchens, low planning effort, and places where a second round feels natural.", ranking: ["Open now", "Shared plates", "Walkability", "Post-meal linger"], sortOrder: 1 },
    { key: "date", query: "good date spot nearby", label: "Low-pressure date", thesis: "Rank for conversational intimacy, graceful exits, and nearby second-stop options.", ranking: ["Talkability", "Warmth", "Exit ease", "Second stop"], sortOrder: 2 },
    { key: "lunch", query: "cheap lunch around this office", label: "Office lunch", thesis: "Bias toward price, queue speed, seating confidence, and easy group splitting.", ranking: ["Price", "Queue speed", "Group fit", "Repeat value"], sortOrder: 3 },
    { key: "friend", query: "low-pressure friend hang nearby", label: "Friendship loop", thesis: "Surface places that make it easy to ask, repeat, and build a routine.", ranking: ["Ask ease", "Repeat cadence", "Vulnerability room", "Host path"], sortOrder: 4 },
  ]);

  await db.insert(places).values([
    { intent: "work", sortOrder: 0, name: "Archive Table", category: "Cafe and reading room", distance: "0.4 mi", eta: "7 min walk", price: "$$", score: 94, vibe: "Quiet, steady, laptop-tolerant", bestFor: "Two focused hours with a soft check-in after.", why: ["Review language mentions calm tables and non-rushed service.", "Long communal counter makes working near someone feel normal.", "Closes after the afternoon slump, so it can become a weekly block."], signals: [{ label: "Noise", value: 92 }, { label: "Seating", value: 88 }, { label: "Routine", value: 84 }], followThroughInvitation: "I am doing a 90-minute work sprint here Tuesday. Want the other side of the table?", followThroughRitual: "Same table, same two-hour block, optional walk after.", followThroughFriction: "Low: no big ask, no fixed conversation requirement.", x: 62, y: 34, color: "#1f6b5d" },
    { intent: "work", sortOrder: 1, name: "Pollen Bench", category: "Plant shop cafe", distance: "0.8 mi", eta: "12 min walk", price: "$$", score: 87, vibe: "Bright, gentle, good background life", bestFor: "Casual co-working that can become a plant-care errand.", why: ["Tables are smaller, but the room is calmer than nearby chains.", "Plants and shelves create natural conversation prompts.", "A recurring errand makes the repeat invite feel practical."], signals: [{ label: "Noise", value: 82 }, { label: "Seating", value: 76 }, { label: "Routine", value: 91 }], followThroughInvitation: "I am checking out the plant corner after coffee. Want to come for one focused hour?", followThroughRitual: "Monthly plant browse plus work sprint.", followThroughFriction: "Medium: seating is not guaranteed after 2 PM.", x: 38, y: 48, color: "#8a6d2f" },
    { intent: "work", sortOrder: 2, name: "Kiln House", category: "Bakery cafe", distance: "1.1 mi", eta: "5 min ride", price: "$", score: 81, vibe: "Warm, busy, fast reset", bestFor: "A short working session before a shared snack.", why: ["Strong value and reliable tables before lunch.", "The pastry counter gives a built-in break point.", "Better for 45 minutes than a whole afternoon."], signals: [{ label: "Noise", value: 64 }, { label: "Seating", value: 78 }, { label: "Routine", value: 74 }], followThroughInvitation: "I am going early before it fills up. Want to do one task each and split something sweet?", followThroughRitual: "Friday task closeout with a pastry split.", followThroughFriction: "Medium: gets loud during lunch rush.", x: 74, y: 66, color: "#b6522b" },
    { intent: "supper", sortOrder: 0, name: "Moon Wok", category: "Late-night noodles", distance: "0.3 mi", eta: "5 min walk", price: "$", score: 96, vibe: "Open, unfussy, generous portions", bestFor: "The text after a long day when nobody wants to plan.", why: ["Open until 2 AM with consistent last-order reliability.", "Shared sides make the invite feel less intense.", "Counter seats work for two people or a small group."], signals: [{ label: "Open", value: 98 }, { label: "Ease", value: 94 }, { label: "Linger", value: 78 }], followThroughInvitation: "I am doing emergency noodles after work. Zero ceremony. Want in?", followThroughRitual: "Last Thursday supper for whoever is still awake.", followThroughFriction: "Low: cheap, late, no booking required.", x: 58, y: 58, color: "#b6522b" },
    { intent: "supper", sortOrder: 1, name: "Afterglow Satay", category: "Street grill", distance: "0.9 mi", eta: "10 min ride", price: "$$", score: 88, vibe: "Smoky, social, easy to add people", bestFor: "A loose group supper after an event.", why: ["Outdoor tables reduce the pressure of a formal hang.", "Skewers are easy to split across changing group sizes.", "Nearby dessert stop creates a natural continuation."], signals: [{ label: "Open", value: 89 }, { label: "Ease", value: 86 }, { label: "Linger", value: 91 }], followThroughInvitation: "A few of us might grab satay after. If you want a low-key decompression, come by.", followThroughRitual: "Post-event supper table, no RSVP pressure.", followThroughFriction: "Medium: weather affects comfort.", x: 34, y: 62, color: "#1f6b5d" },
    { intent: "supper", sortOrder: 2, name: "The Blue Kettle", category: "Tea and congee", distance: "1.2 mi", eta: "8 min ride", price: "$", score: 82, vibe: "Soft, restorative, quiet enough", bestFor: "A vulnerable catch-up after a hard week.", why: ["Warm food, soft lighting, and small tables support deeper conversation.", "Lower crowd energy than bars at the same hour.", "Menu is simple enough to avoid decision fatigue."], signals: [{ label: "Open", value: 82 }, { label: "Ease", value: 80 }, { label: "Linger", value: 84 }], followThroughInvitation: "This week was a lot. Want congee and a quiet reset, no need to be interesting?", followThroughRitual: "Soft landing supper when the week runs long.", followThroughFriction: "Low: emotionally honest without being performative.", x: 70, y: 28, color: "#2f607f" },
    { intent: "date", sortOrder: 0, name: "Little Lantern", category: "Wine bar and small plates", distance: "0.6 mi", eta: "9 min walk", price: "$$$", score: 93, vibe: "Warm, close, not theatrical", bestFor: "A first or second date where conversation matters.", why: ["Tables are spaced enough for privacy without feeling isolated.", "Menu supports a short drink or a longer meal.", "Two nearby second stops make momentum optional."], signals: [{ label: "Talk", value: 92 }, { label: "Warmth", value: 94 }, { label: "Exit", value: 84 }], followThroughInvitation: "Want to do one drink at Little Lantern, and if it is easy we can walk to dessert?", followThroughRitual: "One intentional hour, optional second stop.", followThroughFriction: "Medium: price is higher, but the exit is clean.", x: 54, y: 42, color: "#8a3f38" },
    { intent: "date", sortOrder: 1, name: "Glasshouse Steps", category: "Museum cafe", distance: "0.7 mi", eta: "11 min walk", price: "$$", score: 89, vibe: "Daylight, curious, gentle prompts", bestFor: "A date that needs something to look at, not just stare across a table.", why: ["Gallery route gives natural pauses and conversation topics.", "Cafe is calm before evening programming.", "Easy to end after coffee without making it awkward."], signals: [{ label: "Talk", value: 87 }, { label: "Warmth", value: 84 }, { label: "Exit", value: 93 }], followThroughInvitation: "Want to pick one exhibit each and then get coffee after?", followThroughRitual: "Monthly exhibit walk with one question each.", followThroughFriction: "Low: activity carries the first 20 minutes.", x: 42, y: 30, color: "#2f607f" },
    { intent: "date", sortOrder: 2, name: "Paper Moon Courtyard", category: "Dessert courtyard", distance: "1.0 mi", eta: "6 min ride", price: "$$", score: 84, vibe: "Playful, open-air, low commitment", bestFor: "A second stop or quick evening meet.", why: ["Dessert format keeps the time box clear.", "Outdoor seating makes silence less heavy.", "Pairs well after dinner elsewhere."], signals: [{ label: "Talk", value: 78 }, { label: "Warmth", value: 89 }, { label: "Exit", value: 88 }], followThroughInvitation: "No dinner logistics. Want to just get dessert and take a short walk?", followThroughRitual: "Dessert-first dates when planning fatigue is high.", followThroughFriction: "Low: clear scope and low time risk.", x: 74, y: 70, color: "#c7812f" },
    { intent: "lunch", sortOrder: 0, name: "Corner Tiffin", category: "Lunch counter", distance: "0.2 mi", eta: "4 min walk", price: "$", score: 95, vibe: "Fast, cheap, reliable", bestFor: "A recurring office lunch without calendar drama.", why: ["High value meals and quick queue turnover.", "Four-seat tables are usually available before 12:20.", "Ordering is simple enough for mixed preferences."], signals: [{ label: "Price", value: 96 }, { label: "Speed", value: 91 }, { label: "Group", value: 88 }], followThroughInvitation: "I am making Corner Tiffin my Wednesday reset. Want to make it a standing 30?", followThroughRitual: "Wednesday office lunch, same window, no agenda.", followThroughFriction: "Low: cheap and close enough to repeat.", x: 49, y: 52, color: "#b6522b" },
    { intent: "lunch", sortOrder: 1, name: "Green Tray", category: "Salad and grain bowls", distance: "0.5 mi", eta: "8 min walk", price: "$$", score: 86, vibe: "Bright, efficient, flexible", bestFor: "A healthier team lunch that does not become a debate.", why: ["Menu handles dietary constraints without custom negotiation.", "Mobile ordering reduces queue uncertainty.", "Nearby benches create overflow seating."], signals: [{ label: "Price", value: 74 }, { label: "Speed", value: 89 }, { label: "Group", value: 91 }], followThroughInvitation: "I am pre-ordering Green Tray at noon. Want me to send the group link?", followThroughRitual: "Low-friction lunch loop for the office cluster.", followThroughFriction: "Medium: slightly pricier than the counter spots.", x: 32, y: 40, color: "#1f6b5d" },
    { intent: "lunch", sortOrder: 2, name: "Steam Alley", category: "Dumpling shop", distance: "0.7 mi", eta: "10 min walk", price: "$", score: 83, vibe: "Busy, communal, good chaos", bestFor: "A small group that wants energy more than privacy.", why: ["Shared baskets make cost splitting easy.", "Counter service means no long bill ritual.", "Louder room is better for casual teammates than serious catch-ups."], signals: [{ label: "Price", value: 92 }, { label: "Speed", value: 78 }, { label: "Group", value: 79 }], followThroughInvitation: "Dumpling run at 12:15. We can be back before the 1 PM call.", followThroughRitual: "Deadline-day dumpling run.", followThroughFriction: "Medium: less ideal for sensitive conversations.", x: 68, y: 46, color: "#8a6d2f" },
    { intent: "friend", sortOrder: 0, name: "Common Room", category: "Bookstore cafe", distance: "0.5 mi", eta: "8 min walk", price: "$$", score: 97, vibe: "Calm, familiar, generous with time", bestFor: "Turning a good first conversation into a standing low-pressure hang.", why: ["Browsing gives people something to do before vulnerability is earned.", "The seating layout supports one-on-one and small group formats.", "Weekly programming creates a reason to come back without event hopping."], signals: [{ label: "Ask ease", value: 96 }, { label: "Repeat", value: 94 }, { label: "Depth", value: 89 }], followThroughInvitation: "I am going to browse for 20 minutes and read for 40. Want to join, no pressure to talk the whole time?", followThroughRitual: "Sunday shelf browse plus one shared recommendation.", followThroughFriction: "Low: parallel play makes the invite safer.", x: 56, y: 38, color: "#1f6b5d" },
    { intent: "friend", sortOrder: 1, name: "Long Table Studio", category: "Community craft table", distance: "0.9 mi", eta: "13 min walk", price: "$$", score: 91, vibe: "Hands busy, conversation optional", bestFor: "People who connect better while making something.", why: ["Activities reduce the pressure to perform socially.", "Open table format makes inviting a third person simple.", "A visible project creates continuity across visits."], signals: [{ label: "Ask ease", value: 88 }, { label: "Repeat", value: 96 }, { label: "Depth", value: 86 }], followThroughInvitation: "I am going to make something badly on purpose. Want to sit at the long table with me?", followThroughRitual: "Fortnightly bad crafts, snacks after.", followThroughFriction: "Medium: requires more time than coffee.", x: 36, y: 64, color: "#8a3f38" },
    { intent: "friend", sortOrder: 2, name: "Harbor Steps", category: "Public seating and tea cart", distance: "1.1 mi", eta: "9 min ride", price: "$", score: 86, vibe: "Open, slow, easy to leave", bestFor: "A walk-and-talk when sitting across a table feels too intense.", why: ["Movement lowers social pressure and supports honest conversation.", "Tea cart gives a small anchor without making it a purchase-heavy hang.", "Sunset timing can become a weekly ritual."], signals: [{ label: "Ask ease", value: 93 }, { label: "Repeat", value: 82 }, { label: "Depth", value: 92 }], followThroughInvitation: "Want to grab tea and walk the steps for half an hour? I need air more than a big plan.", followThroughRitual: "Sunset walk, one real question, home before it drags.", followThroughFriction: "Low: free, flexible, and naturally time-boxed.", x: 73, y: 57, color: "#2f607f" },
  ]);

  await db.insert(people).values([
    { intent: "work", sortOrder: 0, name: "Maya", initials: "MA", distance: "0.6 mi", availability: "Tue mornings", match: 94, socialMode: "Parallel work first", wants: "A quiet table buddy for deep work and a short walk after.", repeatSignal: "Open to a weekly focus block.", opener: "I am doing one boring task at Archive Table. Want to be quiet together for 90 minutes?", color: "#1f6b5d" },
    { intent: "work", sortOrder: 1, name: "Jonas", initials: "JO", distance: "0.8 mi", availability: "Thu afternoons", match: 89, socialMode: "Light check-ins", wants: "Someone to co-work near without turning it into a networking thing.", repeatSignal: "Prefers same-place routines.", opener: "Want to do one focus sprint and compare notes only at the end?", color: "#8a6d2f" },
    { intent: "work", sortOrder: 2, name: "Rin", initials: "RI", distance: "1.0 mi", availability: "Flexible lunch break", match: 84, socialMode: "Task then snack", wants: "Short sessions that end with a pastry or errand.", repeatSignal: "Likes low-commitment repeats.", opener: "I am trying Kiln House before it gets loud. Want a 45-minute reset?", color: "#b6522b" },
    { intent: "supper", sortOrder: 0, name: "Theo", initials: "TH", distance: "0.4 mi", availability: "After 10 PM", match: 96, socialMode: "No-plan supper", wants: "Late food with people who do not need the night to become an event.", repeatSignal: "Free most last Thursdays.", opener: "Emergency noodles after work. No performance required. Want in?", color: "#b6522b" },
    { intent: "supper", sortOrder: 1, name: "Anika", initials: "AN", distance: "0.9 mi", availability: "Weekend nights", match: 88, socialMode: "Small group table", wants: "A casual post-event decompression spot with room to add friends.", repeatSignal: "Open to recurring supper crews.", opener: "A few of us may grab satay after. Want to make it a loose table?", color: "#1f6b5d" },
    { intent: "supper", sortOrder: 2, name: "Sam", initials: "SA", distance: "1.1 mi", availability: "Hard weeks", match: 83, socialMode: "Quiet reset", wants: "Warm food and honest conversation without loud bar energy.", repeatSignal: "Prefers opt-in check-ins.", opener: "Want congee and a quiet reset this week? No need to be interesting.", color: "#2f607f" },
    { intent: "date", sortOrder: 0, name: "Leah", initials: "LE", distance: "0.7 mi", availability: "Early evenings", match: 92, socialMode: "One drink first", wants: "A date format with a clean exit and an optional second stop.", repeatSignal: "Likes intentional, short first meets.", opener: "Want to do one drink, then decide if dessert sounds easy?", color: "#8a3f38" },
    { intent: "date", sortOrder: 1, name: "Owen", initials: "OW", distance: "0.9 mi", availability: "Sunday afternoons", match: 88, socialMode: "Activity-led", wants: "Something to look at so the date is not just interview mode.", repeatSignal: "Open to monthly gallery walks.", opener: "Want to pick one exhibit each and get coffee after?", color: "#2f607f" },
    { intent: "date", sortOrder: 2, name: "Nora", initials: "NO", distance: "1.2 mi", availability: "After dinner", match: 84, socialMode: "Dessert walk", wants: "Low-commitment evening plans that do not require a whole dinner.", repeatSignal: "Likes flexible second stops.", opener: "No dinner logistics. Dessert and a short walk?", color: "#c7812f" },
    { intent: "lunch", sortOrder: 0, name: "Priya", initials: "PR", distance: "same building", availability: "Wed 12:15", match: 95, socialMode: "Standing 30", wants: "A reliable lunch crew without calendar negotiation every week.", repeatSignal: "Actively wants recurring office lunches.", opener: "I am making Corner Tiffin my Wednesday reset. Want to make it standing?", color: "#b6522b" },
    { intent: "lunch", sortOrder: 1, name: "Ben", initials: "BE", distance: "0.3 mi", availability: "Noon sharp", match: 87, socialMode: "Fast group order", wants: "Diet-flexible lunches where everyone can order quickly.", repeatSignal: "Will join if ordering is simple.", opener: "I am pre-ordering Green Tray. Want the group link?", color: "#1f6b5d" },
    { intent: "lunch", sortOrder: 2, name: "Iris", initials: "IR", distance: "0.5 mi", availability: "Deadline days", match: 82, socialMode: "Good chaos", wants: "Casual teammate hangs with food that is easy to split.", repeatSignal: "Likes deadline-day rituals.", opener: "Dumpling run at 12:15. Back before the 1 PM call?", color: "#8a6d2f" },
    { intent: "friend", sortOrder: 0, name: "Kai", initials: "KA", distance: "0.5 mi", availability: "Sunday afternoons", match: 98, socialMode: "Parallel play", wants: "A friend hang where silence is allowed and conversation can grow slowly.", repeatSignal: "Looking for an every-other-week rhythm.", opener: "Want to browse for 20 minutes and read for 40, no pressure to talk the whole time?", color: "#1f6b5d" },
    { intent: "friend", sortOrder: 1, name: "Elena", initials: "EL", distance: "0.8 mi", availability: "Thursday nights", match: 91, socialMode: "Make something", wants: "People who connect better while doing something with their hands.", repeatSignal: "Would join a fortnightly craft table.", opener: "I am going to make something badly on purpose. Want to sit at the long table?", color: "#8a3f38" },
    { intent: "friend", sortOrder: 2, name: "Marcus", initials: "MR", distance: "1.1 mi", availability: "Sunset", match: 86, socialMode: "Walk and talk", wants: "A low-cost way to be honest without sitting across a table.", repeatSignal: "Open to weekly walks.", opener: "Want tea and a half-hour walk? I need air more than a big plan.", color: "#2f607f" },
  ]);

  await db.insert(socialTables).values([
    { intent: "work", title: "Quiet work table", time: "Tuesday, 9:30 AM", size: "2 seats open", hostLine: "Focused work first. Optional 10-minute walk after.", ask: "Claim the other side of the table", cadence: "Weekly focus block" },
    { intent: "supper", title: "Emergency noodle crew", time: "Thursday, 10:15 PM", size: "3 seats open", hostLine: "Late food, no ceremony, leave whenever.", ask: "Join the supper thread", cadence: "Last Thursday supper" },
    { intent: "date", title: "One-drink first meet", time: "Friday, 7:00 PM", size: "1 match", hostLine: "A clear hour with an optional second stop.", ask: "Send a low-pressure invite", cadence: "Second stop only if it feels easy" },
    { intent: "lunch", title: "Standing office lunch", time: "Wednesday, 12:15 PM", size: "4 seats open", hostLine: "Cheap, close, back before the next call.", ask: "Start a lunch loop", cadence: "Weekly 30-minute reset" },
    { intent: "friend", title: "Sunday shelf browse", time: "Sunday, 3:00 PM", size: "3 seats open", hostLine: "Browse, read, share one recommendation, no pressure to perform.", ask: "Start a low-pressure table", cadence: "Every other Sunday" },
  ]);

  await sql.end();
  console.log("Seeded successfully.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
